# Generated by zkapi-clientd/scripts/assemble-release.py from the exact release archives.
{ lib, stdenv, fetchurl, makeWrapper, autoPatchelfHook, openssl, cacert }:
let
  version = "0.1.6";
  archives = {
    x86_64-linux = { target = "linux_amd64"; sha256 = "41f9df6c24fd1e1491bc21fcc5be89289525c01f5a850bd64326a85152bbff95"; };
    aarch64-linux = { target = "linux_arm64"; sha256 = "41549a752cdffdace74cdabd872ad71190d7509a9b307e54f5ee0e5f863b7cdf"; };
    x86_64-darwin = { target = "darwin_amd64"; sha256 = "ac9bb3f0f64c3f9c5c271291f38065cb1b008b5d8b2eb5e998ea9b615fc54a12"; };
    aarch64-darwin = { target = "darwin_arm64"; sha256 = "0e045245332fbe5d832d73f4ec1633bada2a5058032dd137b9e447f83bdc86c4"; };
  };
  archive = archives.${stdenv.hostPlatform.system} or
    (throw "zkapi-clientd binary releases do not support ${stdenv.hostPlatform.system}");
in
stdenv.mkDerivation {
  pname = "zkapi-clientd";
  inherit version;
  src = fetchurl {
    url = "https://github.com/ethereum/zkapi/releases/download/clientd-v0.1.6/zkapi-clientd_${version}_${archive.target}.tar.gz";
    inherit (archive) sha256;
  };

  # Native archives have their payload at the top level, without a source root.
  sourceRoot = ".";
  dontConfigure = true;
  dontBuild = true;
  dontStrip = true;
  nativeBuildInputs = [ makeWrapper ] ++ lib.optionals stdenv.hostPlatform.isLinux [ autoPatchelfHook ];
  buildInputs = lib.optionals stdenv.hostPlatform.isLinux [ openssl stdenv.cc.cc.lib ];

  installPhase = ''
    runHook preInstall
    install -Dm755 zkapi-clientd "$out/bin/zkapi-clientd"
    install -Dm755 zkapi-walletd "$out/bin/zkapi-walletd"
    mkdir -p "$out/share/doc/zkapi-clientd" "$out/share/licenses/zkapi-clientd"
    cp -R share/zkapi-clientd "$out/share/zkapi-clientd"
    install -m644 CLI_PACKAGING.md "$out/share/doc/zkapi-clientd/CLI_PACKAGING.md"
    install -m644 LICENSE "$out/share/licenses/zkapi-clientd/LICENSE"
    install -m644 VERSION "$out/share/zkapi-clientd/VERSION"
    ${lib.optionalString stdenv.hostPlatform.isLinux ''
      install -Dm644 zkapi-clientd.service "$out/lib/systemd/user/zkapi-clientd.service"
      substituteInPlace "$out/lib/systemd/user/zkapi-clientd.service" \
        --replace-fail /usr/bin/zkapi-clientd "$out/bin/zkapi-clientd"
    ''}
    # The bundled companion wins over an unrelated executable in the user's PATH.
    # Keep zkapi-walletd unwrapped: its resolved ../share directory locates the proof keys.
    wrapProgram "$out/bin/zkapi-clientd" \
      --prefix PATH : "$out/bin" \
      --set-default SSL_CERT_FILE "${cacert}/etc/ssl/certs/ca-bundle.crt"
    runHook postInstall
  '';

  doInstallCheck = true;
  installCheckPhase = ''
    runHook preInstallCheck
    test "$("$out/bin/zkapi-clientd" version)" = "zkapi-clientd ${version}"
    "$out/bin/zkapi-walletd" --help >/dev/null
    for asset in request.pk request.vk withdrawal.pk withdrawal.vk manifest.json; do
      test -s "$out/share/zkapi-clientd/proof-setup/$asset"
    done
    runHook postInstallCheck
  '';

  meta = {
    description = "Local inference API with private prepaid zkAPI access";
    homepage = "https://github.com/ethereum/zkapi";
    license = lib.licenses.mit;
    mainProgram = "zkapi-clientd";
    platforms = builtins.attrNames archives;
    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];
  };
}
